version: '3'
services:
  web:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mongowe
    environment:
      - NODE_ENV=production
      - DB_HOST=mongo
      - DB_PORT=27017
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
